### ISSUE TITLE
Güvenlik Açığı Bildirimi (Ziyaretçi Defteri)

### ISSUE THREAD

**Issue by OsmanTunahan** [sonsuzus/soysop#1]
Merhaba, @sonsuzus 👋

Bu issue, "Soyum Sopum Net" projesinde bulunan ziyaretçi defteri sayfasında potansiyel güvenlik açıkları hakkında bir uyarı içermektedir. İlgili kodun incelenmesi ve gerekli güvenlik önlemlerinin alınması için bu issue'yi açıyorum.

1. **SQL Injection Riski:**
- SQL sorgularında doğrudan kullanıcı girdileri veri tabanına gönderiliyor bu da potansiyel bir risk teşkil ediyor. **Prepared statements** veya `mysql_real_escape_string` gibi güvenlik önlemleri eklenmelidir.
```php
$isim = mysql_real_escape_string($_POST['isim']);
$zaman = date("d-m-Y H:m");
$mesaj = mysql_real_escape_string($_POST['mesaj']);
$sql = "INSERT INTO defter (isim, zaman, mesaj) VALUES ('$isim', '$zaman', '$mesaj')";
mysql_query($sql, $GLOBALS['baglan']);
```

2. **Cross-Site Scripting (XSS) Riski:**
- Kullanıcı girişleri doğrudan HTML'e eklenmektedir. XSS saldırılarına karşı koruma için `htmlspecialchars` kullanılmalıdır.
```php
echo ("<h3>".htmlspecialchars($row['isim'])." &nbsp;&nbsp;&nbsp;&nbsp; ".htmlspecialchars($row['zaman'])."</h3>");
echo ("<p>".htmlspecialchars($row['mesaj'])."</p>");
```

Saygılarımla,
Osman Tunahan ARIKAN

**Comment by sonsuzus** [comment]
Haklısınız. Teşekkürler. Kodlar çok eski çalışmalarımdı en yakın zamanda düzeltirim.
